name: Pushing to dockerhub

on:
  push:
    branches:
      - main
jobs:
  publish-docker-hub:
    name: Publish image to docker
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: express-app:latest

    
